// Overview › All Issues — every Linear issue grouped by Epic, with item,
// presto-2026 and agent-verdict tallies (generated by `pnpm ada:index`).
import IssueIndex from '../_kit/IssueIndex.vue'

export default {
  title: 'Overview/All Issues',
  parameters: { layout: 'fullscreen' },
}

export const AllIssues = {
  name: 'All Issues',
  render: () => ({ components: { IssueIndex }, template: '<issue-index />' }),
}
